// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxhdjuengpwqtgkyttwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aGRqdWVuZ3B3cXRna3l0dHdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDUzMTYsImV4cCI6MjA3MjgyMTMxNn0.Zpby7BOu7zkPsnqI03p7GSRKVeG_sH9FSYZ5-bSyMec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});